### ISSUE TITLE
部分功能无法使用

### ISSUE THREAD

**Issue by xia-mc** [Lxns-Network/nakuru-project#26]
使用 ```README.md``` 中的示例代码在 ```CPython 3.11``` 上运行，机器人使用 ```go-cqhttp``` 开启正向HTTP和正向Websocket。部分示例功能无法正常工作。包括但不限于：
```python
@app.receiver("GroupMessage")
...
@app.receiver("Notify")
...
```

**日志**    *使用“看”在QQ群中触发*
```python
D:\MinecraftQQBot\venv\Scripts\python.exe D:\MinecraftQQBot\test.py 
D:\MinecraftQQBot\venv\Lib\site-packages\pydantic\_internal\_fields.py:151: UserWarning: Field "model_show" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<CQHTTP.ws_event() done, defined at D:\MinecraftQQBot\venv\Lib\site-packages\nakuru\application.py:61> exception=AttributeError("module 'pydantic' has no attribute 'error_wrappers'")>
Traceback (most recent call last):
  File "D:\MinecraftQQBot\venv\Lib\site-packages\nakuru\application.py", line 76, in ws_event
    received_data = MessageTypes[received_data["message_type"]].parse_obj(received_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MinecraftQQBot\venv\Lib\site-packages\pydantic\main.py", line 1072, in parse_obj
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MinecraftQQBot\venv\Lib\site-packages\pydantic\main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 7 validation errors for GroupMessage
sender.group_id
  Field required [type=missing, input_value={'age': 0, 'area': '', 'c...', 'user_id': 629995608}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
sender.join_time
  Field required [type=missing, input_value={'age': 0, 'area': '', 'c...', 'user_id': 629995608}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
sender.last_sent_time
  Field required [type=missing, input_value={'age': 0, 'area': '', 'c...', 'user_id': 629995608}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
sender.unfriendly
  Field required [type=missing, input_value={'age': 0, 'area': '', 'c...', 'user_id': 629995608}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
sender.title_expire_time
  Field required [type=missing, input_value={'age': 0, 'area': '', 'c...', 'user_id': 629995608}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
sender.card_changeable
  Field required [type=missing, input_value={'age': 0, 'area': '', 'c...', 'user_id': 629995608}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
sender.shut_up_timestamp
  Field required [type=missing, input_value={'age': 0, 'area': '', 'c...', 'user_id': 629995608}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MinecraftQQBot\venv\Lib\site-packages\nakuru\application.py", line 86, in ws_event
    except pydantic.error_wrappers.ValidationError:
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MinecraftQQBot\venv\Lib\site-packages\pydantic\__init__.py", line 374, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MinecraftQQBot\venv\Lib\site-packages\pydantic\_migration.py", line 306, in wrapper
    raise AttributeError(f'module {module!r} has no attribute {name!r}')
AttributeError: module 'pydantic' has no attribute 'error_wrappers'
```

**附录**
***go-cqhttp部分日志***
```log
Active code page: 65001
[2024-02-16 16:16:55] [INFO]: 当前版本:v1.2.0
[2024-02-16 16:16:55] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2024-02-16 16:16:55] [INFO]: 检查签名服务器：-  (2/2)
[2024-02-16 16:16:55] [INFO]: 检查签名服务器：-  (1/2)
[2024-02-16 16:16:55] [WARNING]: no usable sign server
[2024-02-16 16:16:55] [WARNING]: 警告: 未配置签名服务器或签名服务器不可用, 这可能会导致登录 45 错误码或发送消息被风控
[2024-02-16 16:16:55] [INFO]: 开始尝试登录并同步消息...
[2024-02-16 16:16:55] [INFO]: 使用协议: Android Watch 2.0.8
[2024-02-16 16:16:55] [INFO]: Protocol -> connect to server: 180.109.192.57:8080
[2024-02-16 16:16:55] [WARNING]: Protocol -> device lock is disabled. HTTP API may fail.
[2024-02-16 16:16:58] [INFO]: 收到服务器地址更新通知, 根据配置文件已忽略.
[2024-02-16 16:16:59] [INFO]: 登录成功 欢迎使用: aerfa
[2024-02-16 16:16:59] [INFO]: 开始加载好友列表...
[2024-02-16 16:16:59] [INFO]: 共加载 134 个好友.
[2024-02-16 16:16:59] [INFO]: 开始加载群列表...
[2024-02-16 16:17:03] [INFO]: 共加载 54 个群.
[2024-02-16 16:17:04] [INFO]: 资源初始化完成, 开始处理信息.
[2024-02-16 16:17:04] [INFO]: アトリは、高性能ですから!
[2024-02-16 16:17:04] [INFO]: 正在检查更新.
[2024-02-16 16:17:04] [INFO]: CQ HTTP 服务器已启动: [::]:5700
[2024-02-16 16:17:04] [INFO]: CQ WebSocket 服务器已启动: [::]:8080
[2024-02-16 16:17:04] [INFO]: 接受 WebSocket 连接: 127.0.0.1:51315 (/)
[2024-02-16 16:17:04] [INFO]: 检查更新完成. 当前已运行最新版本.
[2024-02-16 16:17:04] [INFO]: 开始诊断网络情况
[2024-02-16 16:17:06] [INFO]: 网络诊断完成. 未发现问题
[2024-02-16 16:17:25] [INFO]: 收到群 TEST(.........) 内 A肆零-西烛(.........) 的消息: 看 (.........)
```
***go-cqhttp部分配置***
```yml
# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  - http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      version: 11     # OneBot协议版本, 支持 11/12
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
      #- url: ''                # 地址
      #  secret: ''             # 密钥
      #  max-retries: 3         # 最大重试，0 时禁用
      #  retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
      #- url: http://127.0.0.1:5701/ # 地址
      #  secret: ''                  # 密钥
      #  max-retries: 10             # 最大重试，0 时禁用
      #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
  # 正向WS设置
  - ws:
      # 正向WS服务器监听地址
      address: 0.0.0.0:8080
      middlewares:
        <<: *default # 引用默认中间件
```
***完整测试代码***
```python
from nakuru import (
    CQHTTP,
    GroupMessage,
    Notify,
    GroupMessageRecall,
    FriendRequest
)
from nakuru.entities.components import Plain, Image

app = CQHTTP(
    host="127.0.0.1",
    port=8080,
    http_port=5700,
    token="TOKEN" # 可选，如果配置了 Access-Token
)

@app.receiver("GroupMessage")
async def _(app: CQHTTP, source: GroupMessage):
    # 通过纯 CQ 码处理
    if source.raw_message == "戳我":
        await app.sendGroupMessage(source.group_id, f"[CQ:poke,qq={source.user_id}]")
    # 通过消息链处理
    chain = source.message
    if isinstance(chain[0], Plain):
        if chain[0].text == "看":
            await app.sendGroupMessage(source.group_id, [
                Plain(text="给你看"),
                Image.fromFileSystem("D:/好康的.jpg")
            ])

@app.receiver("GroupMessageRecall")
async def _(app: CQHTTP, source: GroupMessageRecall):
    await app.sendGroupMessage(source.group_id, "你撤回了一条消息")

@app.receiver("Notify")
async def _(app: CQHTTP, source: Notify):
    if source.sub_type == "poke" and source.target_id == 114514:
        await app.sendGroupMessage(source.group_id, "不许戳我")

@app.receiver("FriendRequest")
async def _(app: CQHTTP, source: FriendRequest):
    await app.setFriendRequest(source.flag, True)

app.run()
```
